
const list_layoutProps = [
    "alignContent",
    "alignItems",
    "alignSelf",
    "aspectRatio",
    "borderBottomWidth",
    "borderEndWidth",
    "borderLeftWidth",
    "borderRightWidth",
    "borderStartWidth",
    "borderTopWidth",
    "borderWidth",
    "bottom",
    "columnGap",
    "direction",
    "display",
    "end",
    "flex",
    "flexBasis",
    "flexDirection",
    "flexGrow",
    "flexShrink",
    "flexWrap",
    "gap",
    "height",
    "justifyContent",
    "left",
    "margin",
    "marginBottom",
    "marginEnd",
    "marginHorizontal",
    "marginLeft",
    "marginRight",
    "marginStart",
    "marginTop",
    "marginVertical",
    "maxHeight",
    "maxWidth",
    "minHeight",
    "minWidth",
    "overflow",
    "padding",
    "paddingBottom",
    "paddingEnd",
    "paddingHorizontal",
    "paddingLeft",
    "paddingRight",
    "paddingStart",
    "paddingTop",
    "paddingVertical",
    "position",
    "right",
    "rowGap",
    "start",
    "top",
    "width",
    "zIndex",
]

const list_viewStyleProps = [
    "backfaceVisibility ",
    "backgroundColor ",
    "borderBottomColor ",
    "borderBottomEndRadius",
    "borderBottomLeftRadius",
    "borderBottomRightRadius",
    "borderBottomStartRadius",
    "borderBottomWidth",
    "borderColor",
    "borderCurveiOS",
    "borderEndColor",
    "borderLeftColor",
    "borderLeftWidth",
    "borderRadius",
    "borderRightColor",
    "borderRightWidth",
    "borderStartColor",
    "borderStyle",
    "borderTopColor",
    "borderTopEndRadius",
    "borderTopLeftRadius",
    "borderTopRightRadius",
    "borderTopStartRadius",
    "borderTopWidth",
    "borderWidth",
    "elevationAndroid",
    "opacity",
    "pointerEvents"]

const list_textStyleProps = [
    "color",
    "fontFamily",
    "fontSize",
    "fontStyle",
    "fontWeight",
    "includeFontPaddingAndroid",
    "fontVariant",
    "letterSpacing",
    "lineHeight",
    "textAlign",
    "textAlignVerticalAndroid",
    "textDecorationColoriOS",
    "textDecorationLine",
    "textDecorationStyleiOS",
    "textShadowColor",
    "textShadowOffset",
    "textShadowRadius",
    "textTransform",
    "verticalAlignAndroid",
    "writingDirection"]


const list_shadowStyleProps = [
    "shadowColor",
    "shadowOffsetiOS",
    "shadowOpacityiOS",
    "shadowRadius",
]

const list_allStyleProps = new Set([...list_layoutProps, ...list_viewStyleProps, ...list_textStyleProps, ...list_shadowStyleProps]);


export default function useStyleExtractor(style = {}) {
    const __style = {}
    Object.keys(style).forEach((key) => {
        list_allStyleProps.includes(key) ? __style[key] = style[key] : console.log("useStyleExtractor key not found in list_allStyleProps");
    });
    return Object.freeze(__style);
}