const languagTrans = {
  "home": "home",
  "action": "azioni",
  "settings": "impostazioni",
  "table 1": "tavolo 1",
  "table bill 0": "conto tavolo 0",
  "customers 0": "clienti 0",
  "free": "libero",
  "reserved": "riservato",
  "occupied": "occupato",
  "remove customer from table 0": "rimuovi cliente dal tavolo 0",
  "book table": "riserva tavolo",
  "customer wants to pay": "cliente vuole pagare",
  "delete table": "cancella tavolo",
  "table actions": "azioni del tavolo",
  "add menu item": "aggiungi prodotto menu",
  "submit": "invia",
  "enter food id": "inserisci id piatto",
  "enter food name": "inserisci nome del piatto",
  "enter food price": "inserisci costo del piatto",
  "food ingredients": "ingredienti del piatto",
  "add": "aggiungi",
  "ingredient": "ingrediente",
  "quantity": "quantita`",
  "cost": "costo",
  "cancel": "cancella",
  "chef page": "pagina chef",
  "customer no 2": "cliente numero 2",
  "reject": "rifiuta",
  "ready": "pronto",
  "message for waiter": "messaggio per cameriere",
  "list suppliers": "lista fornitori",
  "listwithsearch": "ricercainlista",
  "search": "cerca",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
  "": "",
};
